version: "3"

tasks:
  generate:logo:
    run: once
    cmds:
      - mkdir -p artifacts
      - for:
          matrix:
            THEME:
              - NAME: white
                STYLE: white
                BACKGROUND_COLOR: none
              - NAME: black
                STYLE: black
                BACKGROUND_COLOR: none
              - NAME: crimson
                STYLE: crimson
                BACKGROUND_COLOR: none
              - NAME: beige
                STYLE: beige
                BACKGROUND_COLOR: none
              - NAME: orange
                STYLE: orange
                BACKGROUND_COLOR: none
              - NAME: white-on-black
                STYLE: white
                BACKGROUND_COLOR: black
              - NAME: black-on-white
                STYLE: black
                BACKGROUND_COLOR: white
              - NAME: crimson-on-beige
                STYLE: crimson
                BACKGROUND_COLOR: "#f3eac0"
            GEOMETRY:
              - SIZE: 64
                PADDING: 2
              - SIZE: 128
                PADDING: 4
              - SIZE: 256
                PADDING: 8
              - SIZE: 512
                PADDING: 32
        cmd: >
          rsvg-convert
          --left={{div (sub .ITEM.GEOMETRY.SIZE ( div (sub .ITEM.GEOMETRY.SIZE (mul .ITEM.GEOMETRY.PADDING 2)) 2 )) 2}}
          --top={{div (sub .ITEM.GEOMETRY.SIZE ( sub .ITEM.GEOMETRY.SIZE (mul .ITEM.GEOMETRY.PADDING 2) )) 2}}
          --page-width={{.ITEM.GEOMETRY.SIZE}}
          --page-height={{.ITEM.GEOMETRY.SIZE}}
          --width={{div (sub .ITEM.GEOMETRY.SIZE (mul .ITEM.GEOMETRY.PADDING 2)) 2}}
          --height={{sub .ITEM.GEOMETRY.SIZE (mul .ITEM.GEOMETRY.PADDING 2)}}
          --stylesheet=src/{{.ITEM.THEME.STYLE}}.css
          --background-color={{.ITEM.THEME.BACKGROUND_COLOR}}
          src/buzbo-logo.svg
          > artifacts/buzbo-logo-{{.ITEM.GEOMETRY.SIZE}}-{{.ITEM.THEME.NAME}}.png
